### ISSUE TITLE
Trailing slashes

### ISSUE THREAD

**Issue by callahm3** [theforeman/puppet-tftp#35]
In manifests::params on line 9, 26, and 34 tftboot has trailing slashes. This is creating issues in the Foreman discovery plugin due to double slashes. Can the trailing slashes be removed?

**Comment by edestecd** [comment]
Creates double slash issue -> https://github.com/theforeman/puppet-foreman_proxy/blob/master/manifests/params.pp#L180

Requires single slash boot dir -> https://github.com/theforeman/puppet-foreman/blob/master/manifests/plugin/discovery.pp#L38

**Comment by edestecd** [comment]
Basically adding the discovery plugin in the foreman module results in this error:
```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Invalid relationship: Foreman::Remote_file[/var/lib/tftpboot/boot/fdi-image-latest.tar] { require => File[/var/lib/tftpboot/boot] }, because File[/var/lib/tftpboot/boot] doesn't seem to be in the catalog
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

**Comment by mmoll** [comment]
please test #36
