### ISSUE TITLE
Failed to call refresh: /usr/sbin/foreman-rake db:migrate returned 1 instead of one of [0]

### ISSUE THREAD

**Issue by bharathjakkani** [theforeman/puppet-tftp#48]
Hi team,

I have installed 'foreman' on my VM. Before I inatall the 'Katello' plugin it was running fine. But once and after installing kateloo when I ran the 'foreman-installer' I get the error below. Please let me know how to resolve this issue.

 /Stage[main]/Foreman::Database/Foreman::Rake[db:migrate]/Exec[foreman-rake-db:migrate]: Failed to call refresh: /usr/sbin/foreman-rake db:m                                igrate returned 1 instead of one of [0]

Foreman version - 1.15
katello version - 3.3.0

Thanks
Bharath J

**Comment by domcleal** [comment]
This isn't the right place to report a bug against the Katello project, please check their website for a bug tracker. This is only for the `tftp` Puppet module.
