### ISSUE TITLE
Unknown resource type: 'xinetd::service' 

### ISSUE THREAD

**Issue by Yamakasi** [theforeman/puppet-tftp#52]
This is the error I get with the foreman-xinetd module installed as well:

Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Resource Statement, Unknown resource type: 'xinetd::service' at /etc/puppetlabs/code/environments/common/tftp/manifests/config.pp:20:7

**Comment by stbenjam** [comment]
Do you have the xinetd module? It's listed as a requirement of this module.

https://github.com/theforeman/puppet-tftp/blob/master/metadata.json#L21-L24

**Comment by Yamakasi** [comment]
Yes it's in and all classes are included, where only the xinetd one is needed as it includes the rest.

**Comment by Yamakasi** [comment]
Fixed, thanks @stbenjam :)
